### ISSUE TITLE
Cortex 3.0 upgrade issue

### ISSUE THREAD

**Issue by papiyachatterjee** [GoogleCloudPlatform/cortex-data-foundation#19]
Hi Team,

We were at cortex 2.0, and now upgrading to Cortex 3.0. However when I run the existing code after the pull I face these issues while table generation.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/19707248/213468939-20cdd1bb-7e54-438d-8d95-afab7dccfbff.png">

Any suggestions would help.

Thank you

**Comment by Lsubatin** [comment]
hi @papiyachatterjee , without any more details on your implementation, I'd guess this is because your [setting.yaml](https://github.com/GoogleCloudPlatform/cortex-dag-generator/blob/e464a1e9fde33ba82d5e55ea8e2cf609e8a60dde/setting.yaml#L253) config file in 2.0 had the default for vbrp  as RUNTIME) and is now switched to behave as a table. I'd recommend not merging configuration files and only adding new values instead, as  your configurations will work for your needs better than the examples we include in them.

If switching the value back to runtime does not fix it, please provide more context on what vbrp looks like today.

**Comment by benschuler** [comment]
Closing this issue as inactive. If there are still open questions, please let us know and we will be happy to assist you.
