### ISSUE TITLE
Permission Denied Error when running with Service Account Impersonation

### ISSUE THREAD

**Issue by limwei-ps** [GoogleCloudPlatform/cortex-data-foundation#79]
<img width="800" alt="Screenshot 2024-09-05 133029" src="https://github.com/user-attachments/assets/adb72c3c-eb5b-41c6-9c51-ebdde910dbab">

I encounter above error where its permission denied whenever .sh files need to be executed. It works fine when I am running the build with default cloud build service account and executing with my own user account. 

I know this is similar to #48 by [jlopez798](https://github.com/GoogleCloudPlatform/cortex-data-foundation/issues?q=is%3Aissue+author%3Ajlopez798) but I don't see any resolution there. I have dropped to cortex support team titled "Cortex Data Foundation Impersonation Service Account Error". 

Could you please support on this. Thanks!

**Comment by benschuler** [comment]
Hi @limwei-ps, 
Thanks for reaching out and reporting this. To help us better understand your specific setup, can you share more information about how you get to the point where you start the deployment?

Typically, we [recommend the following steps](https://github.com/GoogleCloudPlatform/cortex-data-foundation?tab=readme-ov-file#deployment-for-development-or-production-environments):
1. Log on to [console.cloud.google.com](http://console.cloud.google.com/) and select the project you want to use for deployment
2. Open the [Cloud Shell](https://cloud.google.com/shell/docs/launching-cloud-shell) and make sure the project is selected properly
3. Run this command to clone the Cortex repository including all submodules into your Cloud Shell environment: `git clone --recurse-submodules https://github.com/GoogleCloudPlatform/cortex-data-foundation`
4. Move into the repository in your environment: `cd cortex-data-foundation`
5. Make changes to the configuration files so that the deployment fits your needs: `edit config/config.json`
6. Execute the deployment by running this command (replace the parameters with your actual values): `gcloud builds submit --project ${PROJECT_ID} --substitutions=_GCS_BUCKET=${LOG_BUCKET}`

By following these steps, there should not be any permissions errors. If you are running all of this in your local terminal, there might be other local permission issues happening that are not in our control, and therefore very hard to discover or even reproduce on our side, which is why we strongly recommend using Cloud Shell to execute the deployment.

Please let us know if you run into the same issues when following the steps above in Cloud Shell, and in that case please share the full logs of the failed Cloud Build (as a text file, no screenshots please) with us via cortex-support@google.com so we can follow up privately.

**Comment by limwei-ps** [comment]
Hi @benschuler, it works fine when following the recommended steps. Im having the issue only when attempting impersonation. I will be testing out [specify user defined service account in all of the cloudbuild.yaml](https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts#execute_a_build_using_a_config_file) to test out. If that works, I will provide the steps here and close this issue

**Comment by limwei-ps** [comment]
Hi @benschuler, I have tested out the solution from here [specify user defined service account in all of the cloudbuild.yaml](https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts#execute_a_build_using_a_config_file). It works and below are the steps I took. With that, I will close this issue. Thanks! 

1. I already have a service account (SA1) for impersonation which will be the one that triggers the cloud build. 
2. By running gcloud builds get-default-service-account on my specified project, this would be (SA2_default) the service account executing the build. I will be disabling this to create another service account following the principle of least privilege (SA2_user_defined)
3. That means, I will need to specify SA2_user_defined in all the cloudbuild.yaml as shown in the hyperlink
4. The SA1 will need service account user role so that it can use SA2_user_defined roles to execute the build
5. The executing user will need service account token creator so that user can impersonate SA1
